name: Bug Report

about: Create a report to help us improve
title: "[BUG] "
labels: bug
body:

- type: markdown
  attributes:
    value: |
      ## Bug Description
      A clear and concise description of what the bug is.

- type: textarea
  id: steps
  attributes:
    label: Steps to Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. Go to '...'
      2. Click on '....'
      3. Scroll down to '....'
      4. See error
  validations:
    required: true

- type: textarea
  id: expected
  attributes:
    label: Expected Behavior
    description: What you expected to happen.

- type: textarea
  id: actual
  attributes:
    label: Actual Behavior
    description: What actually happened.

- type: textarea
  id: logs
  attributes:
    label: Relevant Logs
    description: Please include any relevant error messages or logs.

- type: dropdown
  id: os
  attributes:
    label: Operating System
    options:
      - Windows
      - macOS
      - Linux
      - Other

- type: dropdown
  id: node
  attributes:
    label: Node.js Version
    options:
      - 16.x
      - 18.x
      - 20.x
      - Other

- type: input
  id: version
  attributes:
    label: MusicDownloader Version
    description: Run `freyr --version` to get the version.
    placeholder: e.g., 1.0.0

- type: textarea
  id: additional
  attributes:
    label: Additional Context
    description: Add any other context about the problem here.
