name: Feature Request

about: Suggest an idea for this project
title: "[FEATURE] "
labels: enhancement
body:

- type: markdown
  attributes:
    value: |
      ## Feature Description
      A clear and concise description of what feature you want to add.

- type: textarea
  id: problem
  attributes:
    label: Problem Statement
    description: What problem are you trying to solve?
    placeholder: I am trying to...

- type: textarea
  id: solution
  attributes:
    label: Proposed Solution
    description: How do you think this could be solved?
    placeholder: I think this could be solved by...

- type: textarea
  id: alternatives
  attributes:
    label: Alternatives Considered
    description: What alternatives have you considered?

- type: textarea
  id: context
  attributes:
    label: Additional Context
    description: Add any other context, screenshots, or links about the feature request.
